#!/usr/bin/env bash

source "$(dirname "$0")/brightness_common.sh"

device_paths=(
    "/sys/class/backlight/intel_backlight"
    "/sys/class/backlight/acpi_video0"
)

device_path=$(find_device_path "${device_paths[@]}")

if [ -z "$device_path" ]; then
    echo -e "${RED}Error: No suitable backlight device found.${RESET}" >&2
    exit 1
fi

apply_brightness_percentage "$1" "$device_path"
exit $?