#!/usr/bin/env bash

log_file="/tmp/suspend-fix-t2.log"

function log() {
	local log_level="$1"
	local event_msg="$2"
	local timestamp
	timestamp=$(date "+%Y-%m-%d %H:%M:%S")
	local level_str="INFO"

	case "$log_level" in
	"-")
		level_str="CRITICAL"
		;;
	"!")
		level_str="ERROR"
		;;
	"*")
		level_str="WARNING"
		;;
	"+")
		level_str="INFO"
		;;
	"#")
		level_str="DEBUG"
		;;
	*)
		level_str="INFO"
		;;
	esac

	echo "[$timestamp] [$level_str] $event_msg" | tee -a "$log_file"
}

function _load_module() {
	module_name="${1//-/_}"
	delay="${2:-0.5}"

	if lsmod | grep -q "^$module_name\\s"; then
		log "*" "Module $1 is already loaded."
		return 0
	fi

	log "#" "Module $1 is not loaded. Loading..."
	/usr/sbin/modprobe "$1"
	log "#" "Waiting ${delay}s for initialization..."
	sleep "$delay"

	if lsmod | grep -q "^$module_name\\s"; then
		log "+" "Module $1 loaded successfully."
		return 0
	fi

	log "!" "Failed to load module $1."
	return 1
}

function _unload_module() {
	module_name="${1//-/_}"
	delay="${2:-0.5}"

	if ! lsmod | grep -q "^$module_name\\s"; then
		log "*" "Module $1 is not loaded, skipping."
		return 0
	fi

	log "#" "Module $1 is loaded. Unloading..."
	if [ "$1" == "apple-bce" ] || [ "$module_name" == "apple_bce" ]; then
		/usr/sbin/rmmod --force "$1"
		sleep "$delay"
		log "#" "Waiting ${delay}s for deinitialization..."

	else
		/usr/sbin/modprobe --remove --remove-holders "$1"
		sleep "$delay"
		log "#" "Waiting ${delay}s for deinitialization..."
	fi

	if ! lsmod | grep -q "^$module_name\\s"; then
		log "+" "Module $1 unloaded successfully."
		return 0
	fi

	log "!" "Failed to unload module $1."
	return 1
}

function _stop_service() {
	service_name=$1
	if /usr/bin/systemctl is-active --quiet "$service_name"; then
		log "+" "Stopping $service_name..."
		log "_" "###########################"
		/usr/bin/systemctl stop "$service_name"
	fi
}

function _start_service() {
	service_name=$1
	if ! /usr/bin/systemctl is-active --quiet "$service_name"; then
		log "+" "Starting $service_name..."
		log "_" "###########################"
		/usr/bin/systemctl start "$service_name"
	else
		log "_" "###########################"
		log "#" "$service_name is already running, Restarting..."
		log "+" "Restarting $service_name..."
		log "_" "###########################"
		/usr/bin/systemctl restart "$service_name"
	fi
}

function load() {
	log "_" "###########################"
	log "+" "Executing load sequence..."
	log "_" "###########################"

	_load_module apple-bce 4
	_load_module hid_appletb_bl
	_load_module hid_appletb_kbd
	_load_module appletbdrm
	_load_module brcmfmac_wcc
	_load_module brcmfmac
	_load_module hci_bcm4377
	_start_service tiny-dfr.service
	_start_service NetworkManager.service
}

function unload() {
	log "_" "###########################"
	log "+" "Executing unload sequence..."
	log "_" "###########################"

	_stop_service tiny-dfr.service
	_stop_service NetworkManager.service
	_unload_module appletbdrm
	_unload_module hid_appletb_bl
	_unload_module hid_appletb_kbd
	_unload_module brcmfmac_wcc
	_unload_module brcmfmac
	_unload_module hci_bcm4377
	_unload_module apple-bce 4
}

function reload() {
	unload
	/usr/bin/sleep 5
	load
}

case "$1" in
load)
	load
	;;
unload)
	unload
	;;
reload)
	reload
	;;
version | v)
	echo "0.1"
	;;
*)
	echo "Usage: $0 load unload reload"
	exit 1
	;;
esac
