#!/usr/bin/env python3
#
#  bdp
#  T2_Linux
#
#  Created by turannul on 07/12/2025.
#  Rewritten in Python on 07/02/2026.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2 of the License.
#
#  See the LICENSE file for more details.

import brightness_common
import os
import sys

# import common utils
sys.path.append("/usr/local/lib/t2linux")
try:
    import t2
except ImportError:
    # fallback for dev environment
    script_dir = os.path.dirname(os.path.abspath(__file__))
    sys.path.append(os.path.join(script_dir, "..", "common"))
    try:
        import t2
    except ImportError:
        print("Error: Could not import t2.py.")
        sys.exit(1)


def main():
    t2.check_root()

    device_paths = [
        "/sys/class/backlight/intel_backlight",
        "/sys/class/backlight/acpi_video0"
    ]

    device_path = brightness_common.find_device_path(device_paths)

    if not device_path:
        print(f"{brightness_common.cRed}Error: No supported display backlight found.{brightness_common.cReset}", file=sys.stderr)
        sys.exit(brightness_common.e_invalid_usage)

    if len(sys.argv) < 2:
        print(f"{brightness_common.cYellow}Usage: {os.path.basename(sys.argv[0])} <percentage> | --show | -s{brightness_common.cReset}", file=sys.stderr)
        sys.exit(brightness_common.e_invalid_usage)

    arg = sys.argv[1]

    if arg == "--show" or arg == "-s":
        brightness_common.show_brightness(device_path)
        sys.exit(0)

    brightness_common.apply_brightness_percentage(arg, device_path)


if __name__ == "__main__":
    main()
