#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    exec sudo "$(command -v "$0")" "$@"
fi

# https://www.shellcheck.net/wiki/SC1091
# shellcheck source="/dev/null"
source "$(dirname "$0")/brightness_common.sh"

device_paths=(
    "/sys/class/leds/apple::kbd_backlight"
    "/sys/class/leds/smc::kbd_backlight"
    # Feel free to add more paths here if needed
)

device_path=$(find_device_path "${device_paths[@]}")

if [ -z "$device_path" ]; then
    echo -e "${RED}Error: No suitable keyboard backlight device found.${RESET}" >&2
    exit 1
fi

apply_brightness_percentage "$1" "$device_path" "brightness"
exit $?